### ISSUE TITLE
Feature for `dart_api_dl.h` 

### ISSUE THREAD

**Issue by rogurotus** [dart-sys/dart-sys#22]
## Description

Ability to use `dart_api_dl.h` instead of `dart_api.h`

## Alternative Solutions

Creating a separate crate for a given feature

## Additional Context

https://github.com/fzyzcjy/flutter_rust_bridge/issues/893

**Comment by rogurotus** [comment]
@gutenfries, what is the action plan, can I already update the PR or is there something blocking?

**Comment by gutenfries** [comment]
@rogurotus I reviewed your PR and left individual comments on what needs to be changed in order to be mergeable into `main`.

here is a list of requirements/goals, IMO: (most of which are pulled directly from your implementation, BTW)

- [ ] add `feature`/`cfg()` support for `dart_api_dl.h` in `build.rs`/`Cargo.toml`
  - I liked the implementation that you initially went with, IMO we should reimplement the same/similar method w/ two generated modules that are mutually exclusively enabled by `cfg()` feature flags.

- [ ] Integrate required Dart-SDK C/C++ headers directly into Dart-sys.
  - [ ] Add `update_dart_sdk` crate to the root of the repo.
    - [ ] Set up GitHub Actions to run the crate either daily, bidaily, or weekly to continuously keep Dart-sys up to date.

- [ ] Be sure that all tests still pass and that no functionality is broken.
- [ ] Document any hand-written code.

I am willing to do any/all of this, just let me know what your thoughts are :)

**Comment by rogurotus** [comment]
It would be great if you have time for this.

**Comment by gutenfries** [comment]
Not a problem! 

I've already started on a similar implementation.

A production release w/ the `dart_api_dl` should be ready by Monday :)
