### ISSUE TITLE
update licensing

### ISSUE THREAD

**Issue by alexisgeoffrey** [dart-sys/dart-sys#65]
Hello,

Thank you for maintaining this package! I wanted to clarify the license terms on `dart-sys`, it has the license `GPL-3.0-or-later AND MIT AND Apache-2.0` which seems to indicate that any usage/distribution/etc is governed by all three licenses at the same time. Is this intended? Or was the intent to be able to choose between the three? (In which case it should be `GPL-3.0-or-later OR MIT OR Apache-2.0`)

Thank you for your time.

**Comment by gutenfries** [comment]
Hi Alexis,

Thank you for your interest in Dart-Sys!

The licensing is outdated, however, should and will be updated to `MIT AND GPL-3.0-or-later`.

portions of external source code included in `dart-sys` are licensed under `MIT`, and other code which has since been removed was licensed under `Apache-2.0`.

It is the wishes of the authors to license `dart-sys` under the `GPL-3.0-or-later` license, thus requiring BOTH licenses to be followed

Hope this clears any confusion up for you!

**Comment by alexisgeoffrey** [comment]
Sorry for the late response. Thank you, that does clear it up! It might be helpful to users of https://github.com/fzyzcjy/flutter_rust_bridge to be warned about this, since their Rust component package is licensed under `MIT` but one of its core dependencies (`dart-sys`) is GPL. But that might be something to bring up in their own issue tracker.

**Comment by gutenfries** [comment]
Hi folks,

If you're here and haven't yet read https://github.com/fzyzcjy/flutter_rust_bridge/issues/1415, please take a moment to do so.

**Comment by gutenfries** [comment]
resolved with #73
